# Generated by Django 5.2.3 on 2025-06-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('completed', 'Échangé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('product_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_offered', to='products.product', verbose_name='Produit proposé')),
                ('product_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_requested', to='products.product', verbose_name='Produit demandé')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_proposed', to=settings.AUTH_USER_MODEL, verbose_name='Proposeur')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Échange',
                'verbose_name_plural': 'Échanges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit concerné')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (FCFA)')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Retrait en main propre'), ('delivery', 'Livraison à domicile')], default='pickup', max_length=20, verbose_name='Mode de livraison')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('pickup_location', models.TextField(blank=True, verbose_name='Lieu de rendez-vous')),
                ('buyer_notes', models.TextField(blank=True, verbose_name="Notes de l'acheteur")),
                ('seller_notes', models.TextField(blank=True, verbose_name='Notes du vendeur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition")),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'achèvement")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit concerné')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur 1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur 2')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('user1', 'user2', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Note')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'avis")),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Recommande cet utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'avis")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Commande')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur évalué')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'reviewer')},
            },
        ),
    ]
